# Generated by Django 2.2.17 on 2021-01-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="price",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="tasker",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="timestamp_created",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="tip",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="tracking_id",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="transaction",
        ),
        migrations.RemoveField(
            model_name="taskerpaymentaccount",
            name="account_token",
        ),
        migrations.RemoveField(
            model_name="taskerpaymentaccount",
            name="payment_account",
        ),
        migrations.RemoveField(
            model_name="taskerpaymentaccount",
            name="wallet",
        ),
        migrations.RemoveField(
            model_name="taskerwallet",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="taskerwallet",
            name="expiration_date",
        ),
        migrations.RemoveField(
            model_name="taskerwallet",
            name="tasker",
        ),
    ]
